apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-agent-registry-agent-registry-service
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Agent Registry Service
    source:
      repo: https://github.com/vandnagarggoogle/terraform-google-agent-registry.git
      sourceType: git
      dir: /modules/agent-registry-service
    version: 0.0.15
    actuationTool:
      flavor: Terraform
      version: ">= 0.13"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: The project ID to deploy to.
        varType: string
        required: true
      - name: location
        description: The location of the resource.
        varType: string
        required: true
      - name: service_id
        description: The name of the service.
        varType: string
        required: true
      - name: display_name
        description: User-defined display name for the Service (max 63 characters).
        varType: string
      - name: description
        description: The description of the service.
        varType: string
      - name: interfaces
        description: The connection details for the Service.
        varType: |-
          list(object({
              url              = string
              protocol_binding = string # JSONRPC, GRPC, or HTTP_JSON
            }))
        defaultValue: []
        connections:
          - source:
              source: github.com/vandnagarggoogle/terraform-google-agent-registry//modules/agent-registry-endpoint
              version: ">= v0.0.8"
            spec:
              outputExpr: endpoint_interfaces
          # Discovery: From existing MCP Server
          - source:
              source: github.com/vandnagarggoogle/terraform-google-agent-registry//modules/agent-registry-mcp-server
              version: ">= v0.0.8"
            spec:
              outputExpr: mcp_server_interfaces
          # Infra: From Global Load Balancer
          - source:
              source: github.com/terraform-google-modules/terraform-google-lb-http//modules/backend
            spec:
              outputExpr: "{\"url\": apphub_service_uri[0].service_uri, \"protocol_binding\": \"HTTP_JSON\"}"
          # Infra: From Private Service Connect Producer
          - source:
              source: github.com/terraform-google-modules/terraform-google-network//modules/private-service-connect-producer
              version: ">= v15.0.0"
            spec:
              outputExpr: "{\"url\": service_attachment_self_link, \"protocol_binding\": \"HTTP_JSON\"}"
          # Infra: From Cloud Function
          - source:
              source: github.com/GoogleCloudPlatform/terraform-google-cloud-functions
            spec:
              outputExpr: "{\"url\": function_uri, \"protocol_binding\": \"HTTP_JSON\"}"
      - name: agent_spec
        description: The spec of the Agent. Mutually exclusive with mcp_server_spec and endpoint_spec.
        varType: |-
          object({
              type    = string # NO_SPEC or A2A_AGENT_CARD
              content = string # JSON format content
            })
        connections:
          - source:
              source: github.com/vandnagarggoogle/terraform-google-agent-registry//modules/agent-registry-service
              version: ">= v0.0.8"
            spec:
              outputExpr: agent
          - source:
              source: github.com/vandnagarggoogle/terraform-google-agent-registry//modules/agent-registry-agent
              version: ">= v0.0.8"
            spec:
              outputExpr: '{"type": "A2A_AGENT_CARD", "content": agent_id}'
      - name: mcp_server_spec
        description: The spec of the MCP Server. Mutually exclusive with agent_spec and endpoint_spec.
        varType: |-
          object({
              type    = string # NO_SPEC or TOOL_SPEC
              content = string # JSON format content
            })
        connections:
          - source:
              source: github.com/vandnagarggoogle/terraform-google-agent-registry//modules/agent-registry-service
              version: ">= v0.0.8"
            spec:
              outputExpr: mcp_server
          - source:
              source: github.com/vandnagarggoogle/terraform-google-agent-registry//modules/agent-registry-mcp-server
              version: ">= v0.0.8"
            spec:
              outputExpr: '{"type": "TOOL_SPEC", "content": mcp_server_id}'
      - name: endpoint_spec
        description: The spec of the Endpoint. Mutually exclusive with agent_spec and mcp_server_spec.
        varType: |-
          object({
              type = string # NO_SPEC
            })
        connections:
          - source:
              source: github.com/vandnagarggoogle/terraform-google-agent-registry//modules/agent-registry-service
              version: ">= v0.0.8"
            spec:
              outputExpr: endpoint
          - source:
              source: github.com/vandnagarggoogle/terraform-google-agent-registry//modules/agent-registry-endpoint
              version: ">= v0.0.8"
            spec:
              outputExpr: '{"type": "NO_SPEC"}'
    outputs:
      - name: agent
        description: Details of the Agent configuration.
      - name: create_time
        description: The timestamp when the resource was created.
      - name: endpoint
        description: Details of the Endpoint configuration.
      - name: id
        description: The ID of the Agent Registry Service.
      - name: mcp_server
        description: Details of the MCP Server configuration.
      - name: update_time
        description: The timestamp when the resource was updated.
  requirements:
    roles:
      - level: PROJECT
        roles:
          - roles/agentregistry.admin
          - roles/iam.serviceAccountUser
          - roles/config.agent
          - roles/storage.admin
          - roles/networkservices.admin
          - roles/networksecurity.admin
          - roles/serviceusage.serviceUsageAdmin
    services:
      - agentregistry.googleapis.com
      - apphub.googleapis.com
      - aiplatform.googleapis.com
      - serviceusage.googleapis.com
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
    providerVersions:
      - source: hashicorp/google-beta
        version: ">= 7.21.0"
      - source: hashicorp/google-nightly
        version: 2026.3.23-0.0.3
