apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-agent-registry-agent-registry-endpoint
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Agent Registry Endpoint
    source:
      repo: https://github.com/vandnagarggoogle/terraform-google-agent-registry.git
      sourceType: git
      dir: /modules/agent-registry-endpoint
    version: 0.0.2
    actuationTool:
      flavor: Terraform
      version: ">= 0.13"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which the resource belongs.
        varType: string
        required: true
      - name: location
        description: The location of the Agent Registry resource (e.g., us-central1).
        varType: string
        required: true
      - name: filter
        description: A filter string to find the Endpoint
        varType: string
      - name: endpoint_id
        description: The system-generated ID for a generic endpoint.
        varType: string
    outputs:
      - name: endpoint_attributes
        description: Custom attributes associated with the endpoint.
      - name: endpoint_create_time
        description: The timestamp when the endpoint was created.
      - name: endpoint_description
        description: The description of the endpoint.
      - name: endpoint_display_name
        description: The display name of the endpoint.
      - name: endpoint_interfaces
        description: The connection details (URL and protocol binding) for the Endpoint.
      - name: endpoint_update_time
        description: The timestamp when the endpoint was last updated.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google-beta
        version: ">= 7.21.0"
      - source: hashicorp/google-nightly
        version: 2026.3.23-0.0.3
