# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-agent-registry-agent-registry-mcp-server
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Agent Registry MCP Server
    source:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-agent-registry.git
      sourceType: git
      dir: /modules/agent-registry-mcp-server
    version: 0.2.0
    actuationTool:
      flavor: Terraform
      version: ">= 0.13"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: agent-registry-agent
        location: examples/agent-registry-agent
      - name: agent-registry-endpoint
        location: examples/agent-registry-endpoint
      - name: agent-registry-mcp-server
        location: examples/agent-registry-mcp-server
      - name: agent-registry-service
        location: examples/agent-registry-service
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which the resource belongs.
        varType: string
        required: true
      - name: location
        description: The location of the Agent Registry resource (e.g., us-central1).
        varType: string
        required: true
      - name: filter
        description: "A filter string to find the Mcp server "
        varType: string
        connections:
          - source:
              source: github.com/GoogleCloudPlatform/terraform-google-agent-registry//modules/agent-registry-service
              version: ">= v0.0.8"
            spec:
              outputExpr: discovery_filter
      - name: mcp_server_id
        description: The system-generated ID for an MCP server (e.g., agentregistry-0000...).
        varType: string
    outputs:
      - name: mcp_server_attributes
        description: Attributes associated with the MCP Server.
      - name: mcp_server_description
        description: The description of the MCP Server.
      - name: mcp_server_display_name
        description: The display name of the MCP Server.
      - name: mcp_server_id
        description: The unique identifier for the MCP server.
      - name: mcp_server_interfaces
        description: The connection details (URL and protocol binding) for the MCP Server.
      - name: mcp_server_tools
        description: The list of tools available with the MCP Server, including their names, descriptions, and annotations.
      - name: mcp_server_urn
        description: The logical URN of the MCP server.
        type: string
  requirements:
    roles:
      - level: Project
        roles:
          - roles/iam.serviceAccountUser
          - roles/config.agent
          - roles/storage.admin
          - roles/networkservices.admin
          - roles/networksecurity.admin
          - roles/serviceusage.serviceUsageAdmin
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google-beta
        version: ">= 7.21.0"
      - source: hashicorp/google-nightly
        version: 0.2.0.0.3
